# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PerfectFilter
                                 A QGIS plugin
 This plugin offers a more intuitive way to filter information from one or more layers through a user friendly interface.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-09
        copyright            : (C) 2022 by Francisco Contreras
        email                : franciscocontreras93@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PerfectFilter class from file PerfectFilter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PerfectFilter import PerfectFilter
    return PerfectFilter(iface)
